name: run api testing
on:
  push:
    branches: [dev, master]
  pull_request:
    branches: [master]

jobs: 
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    env:
          DATABASE: ${{secrets.DATABASE}}
          TEST_DATABASE: ${{secrets.TEST_DATABASE}}
          AWS_ACCESS_KEY_ID: ${{secets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm test
        
      - name: Install EB CLI
        run:
          npm update -g npm
          npm install aws-cli
      
      - name: Deploy to Elasti Beanstalk
        run:
          eb deploy
