name: run api testing
on:
  push:
    branches: [dev, master]
  pull_request:
    branches: [master]

jobs: 
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm test
        env:
          DATABASE: ${{secrets.DATABASE}}
          TEST_DATABASE: ${{secrets.TEST_DATABASE}}
